# Baixo a imagem padrão do PHP 8 com apache
FROM php:8.0-apache

# Instalo alguns módulos necessários na imagem
RUN apt update \
        && apt install -y \
            g++ \
            libicu-dev \
            libpq-dev \
            libzip-dev \
            zip \
            zlib1g-dev \
        && docker-php-ext-install \
            intl \
            opcache \
            pdo \
            pdo_pgsql \
            pgsql

# Instalo o Xdebug para o PHP
RUN pecl install xdebug

# Adiciono suporte para a ferramenta de CRON
RUN apt-get -y install -qq --force-yes cron

# Defino o workdir como o do projeto
WORKDIR /var/www/html/src

# Baixo o composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Habilito o mod Rewrite do Apache para permitir que novas rotas sejam acessadas no projeto
RUN a2enmod rewrite

# Exponho a porta do Debugger
EXPOSE 9003